name = "mind-luster-api"
main = "src/index.js"
compatibility_date = "2024-11-01"

# D1 database binding
[[d1_databases]]
binding = "DB"          # available as env.DB in the Worker
database_name = "mind_luster_db"
database_id = "07c32377-8399-454d-a58d-e167772b80b4"         # will be filled by wrangler when you create the DB

[vars]
# Add CORS allowlist if you want to restrict origins later
# ALLOW_ORIGIN = "*"
